import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // {
  //this was in original body classname but I don't think it's necessary
  //   `${geistSans.variable} ${geistMono.variable} antialiased`;
  // }
  return (
    <html lang="en" className="light">
      <body
        className={cn('min-h-screen font-sans antialiased grainy', inter.className)}
      >
      <Navbar />
        {children}
      </body>
    </html>
  );
}
